import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "@/store/StoreProvider";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const gruntGrotesk = localFont({
  src: "../assets/fonts/GruntGrotesk-Bold.woff2",
  variable: "--font-grunt-grotesk",
});

export const metadata: Metadata = {
  title: "SamBee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${gruntGrotesk.variable} antialiased bg-black text-white`}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
