"""fix_inspections_final

Revision ID: 7e36f682eecb
Revises: d25ce7f0b55f
Create Date: 2026-04-27 22:29:38.588420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e36f682eecb'
down_revision: Union[str, None] = 'd25ce7f0b55f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
