"""create_inspections_table

Revision ID: e18df34eb31c
Revises: 5c9c9ed0d36b
Create Date: 2026-04-27 22:19:49.531896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18df34eb31c'
down_revision: Union[str, None] = '5c9c9ed0d36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
